Repository xrOxygen/xray-oxygen, pull requests merged in 2018-06, with the labels that each got.

#162 * EDIT: Correct sunlight orientation
  code/engine.vc2008/xrRender/xrRender/LightTrack.cpp
  code/engine.vc2008/xrRender/xrRender/Light_DB.cpp
  code/engine.vc2008/xrRender/xrRender/Light_DB.h
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2.h
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2_R_render.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2_R_sun.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2_rendertarget_accum_direct.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2_rendertarget_phase_combine.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/r2_R_sun.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/r3.h
  code/engine.vc2008/xrRender/xrRenderPC_R3/r3_R_render.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/r3_rendertarget_accum_direct.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/r3_rendertarget_phase_combine.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/r2_R_sun.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/r4.h
  code/engine.vc2008/xrRender/xrRenderPC_R4/r4_R_render.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/r4_rendertarget_accum_direct.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/r4_rendertarget_phase_combine.cpp
Labels: Graphics

#163 * ADD: Custom loadscreen window
  code/engine.vc2008/FrayBuildConfig.hpp
  code/engine.vc2008/Include/xrRender/ApplicationRender.h
  code/engine.vc2008/Include/xrRender/FactoryPtr.h
  code/engine.vc2008/Include/xrRender/RenderFactory.h
  code/engine.vc2008/xrEngine/ILoadingScreen.h
  code/engine.vc2008/xrEngine/device.cpp
  code/engine.vc2008/xrEngine/x_ray.cpp
  code/engine.vc2008/xrEngine/x_ray.h
  code/engine.vc2008/xrEngine/xrEngine.vcxproj
  code/engine.vc2008/xrEngine/xrEngine.vcxproj.filters
  code/engine.vc2008/xrEngine/xr_ioc_cmd.cpp
  code/engine.vc2008/xrGame/GamePersistent.cpp
  code/engine.vc2008/xrGame/GamePersistent.h
  code/engine.vc2008/xrGame/Level_network_start_client.cpp
  code/engine.vc2008/xrGame/game_expression_delegates.cpp
  code/engine.vc2008/xrGame/game_sv_base.cpp
  code/engine.vc2008/xrGame/ui/UIHudStatesWnd.cpp
  code/engine.vc2008/xrGame/ui/UILoadingScreen.cpp
  code/engine.vc2008/xrGame/ui/UILoadingScreen.h
  code/engine.vc2008/xrGame/ui/UIMotionIcon.cpp
  code/engine.vc2008/xrGame/ui/UIMotionIcon.h
  code/engine.vc2008/xrGame/ui/UIProgressBar.cpp
  code/engine.vc2008/xrGame/ui/UIProgressBar.h
  code/engine.vc2008/xrGame/ui/UIXmlInit.cpp
  code/engine.vc2008/xrGame/xrGame.vcxproj
  code/engine.vc2008/xrGame/xrGame.vcxproj.filters
  code/engine.vc2008/xrRender/xrRender/dxApplicationRender.cpp
  code/engine.vc2008/xrRender/xrRender/dxApplicationRender.h
  code/engine.vc2008/xrRender/xrRender/dxRenderFactory.cpp
  code/engine.vc2008/xrRender/xrRender/dxRenderFactory.h
  code/engine.vc2008/xrRender/xrRender/xrRender_console.cpp
  code/engine.vc2008/xrRender/xrRender/xrRender_console.h
  code/engine.vc2008/xrRender/xrRenderPC_R2/xrRender_R2.vcxproj
  code/engine.vc2008/xrRender/xrRenderPC_R2/xrRender_R2.vcxproj.filters
  code/engine.vc2008/xrRender/xrRenderPC_R3/xrRender_R3.vcxproj
  code/engine.vc2008/xrRender/xrRenderPC_R3/xrRender_R3.vcxproj.filters
  code/engine.vc2008/xrRender/xrRenderPC_R4/xrRender_R4.vcxproj
  code/engine.vc2008/xrRender/xrRenderPC_R4/xrRender_R4.vcxproj.filters
  code/utils/xrAI/RCa14252
  game/gamedata/configs/ui/actor_menu.xml
  game/gamedata/configs/ui/actor_menu_16.xml
  game/gamedata/configs/ui/textures_descr/ui_mm_loading_screen.xml
  game/gamedata/configs/ui/ui_HUD.xml
  game/gamedata/configs/ui/ui_HUD_16.xml
  game/gamedata/configs/ui/ui_mm_loading_screen.xml
  game/gamedata/configs/ui/ui_mm_loading_screen_16.xml
  game/gamedata/configs/weapons/w_knife.ltx
  game/gamedata/textures/ui/electron_18_1024.dds
  game/gamedata/textures/ui/electron_18_1600.dds
  game/gamedata/textures/ui/electron_18_800.dds
Labels: Interface

#164 Added tips for "set_weather" con. command, cl_intersect.h moved to xrCDB.
  code/engine.vc2008/xrCDB/cl_intersect.h
  code/engine.vc2008/xrCDB/xrCDB.vcxproj
  code/engine.vc2008/xrCDB/xrCDB.vcxproj.filters
  code/engine.vc2008/xrCDB/xr_area_raypick.cpp
  code/engine.vc2008/xrEngine/Feel_Vision.cpp
  code/engine.vc2008/xrEngine/cl_intersect.h
  code/engine.vc2008/xrEngine/xrEngine.vcxproj
  code/engine.vc2008/xrEngine/xrEngine.vcxproj.filters
  code/engine.vc2008/xrEngine/xr_efflensflare.cpp
  code/engine.vc2008/xrGame/Actor.cpp
  code/engine.vc2008/xrGame/ActorCameras.cpp
  code/engine.vc2008/xrGame/PHMovementControl.cpp
  code/engine.vc2008/xrGame/console_commands.cpp
  code/engine.vc2008/xrGame/ik_foot_collider.cpp
  code/engine.vc2008/xrPhysics/PHAICharacter.cpp
  code/engine.vc2008/xrPhysics/PHCharacter.cpp
  code/engine.vc2008/xrPhysics/PHSimpleCharacter.cpp
  code/engine.vc2008/xrPhysics/tri-colliderknoopc/dcTriListCollider.cpp
  code/engine.vc2008/xrRender/xrRender/DetailManager.cpp
  code/engine.vc2008/xrRender/xrRender/DetailManager_Decompress.cpp
  code/engine.vc2008/xrRender/xrRender/FSkinned.cpp
  code/engine.vc2008/xrRender/xrRender/SkeletonCustom.cpp
  code/engine.vc2008/xrRender/xrRender/SkeletonX.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R2/light_vis.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R2/r2_rendertarget_enable_scissor.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/light_vis.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R3/r3_rendertarget_enable_scissor.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/light_vis.cpp
  code/engine.vc2008/xrRender/xrRenderPC_R4/r4_rendertarget_enable_scissor.cpp
  code/engine.vc2008/xrSound/SoundRender_Core_Processor.cpp
  code/engine.vc2008/xrSound/xrSound.vcxproj
  code/engine.vc2008/xrSound/xrSound.vcxproj.filters
Labels: Architecture, Debbuging
