Repository xrOxygen/xray-oxygen, pull requests merged in 2018-05, with the labels that each got.

#115 Merge pull request
  code/SDK/libraries/x64/ode.lib
  code/engine.vc2008/FrayBuildConfig.hpp
  code/engine.vc2008/xrGame/ui/UIActorStateInfo.cpp
  code/engine.vc2008/xrGame/ui/UIActorStateInfo.h
  code/xrPlugins.sln
  game/gamedata/configs/ui/actor_menu.xml
  game/gamedata/configs/ui/actor_menu_16.xml
  game/gamedata/configs/ui/color_defs.xml
Labels: Interface

#135 xrServer Client-Server Refactoring
  code/engine.vc2008/xrCore/NET_utils.cpp
  code/engine.vc2008/xrEngine/xr_object_list.cpp
  code/engine.vc2008/xrGame/Actor.cpp
  code/engine.vc2008/xrGame/Actor_Movement.cpp
  code/engine.vc2008/xrGame/Level.cpp
  code/engine.vc2008/xrGame/Level_network.cpp
  code/engine.vc2008/xrGame/Level_network_spawn.cpp
  code/engine.vc2008/xrGame/ShootingObject.cpp
  code/engine.vc2008/xrGame/UIGameSP.cpp
  code/engine.vc2008/xrGame/UIGameSP.h
  code/engine.vc2008/xrGame/Weapon.h
  code/engine.vc2008/xrGame/WeaponKnife.cpp
  code/engine.vc2008/xrGame/alife_switch_manager.cpp
  code/engine.vc2008/xrGame/console_commands.cpp
  code/engine.vc2008/xrGame/game_base.h
  code/engine.vc2008/xrGame/game_cl_base.cpp
  code/engine.vc2008/xrGame/game_cl_base.h
  code/engine.vc2008/xrGame/game_cl_single.cpp
  code/engine.vc2008/xrGame/game_cl_single.h
  code/engine.vc2008/xrGame/level_script.cpp
  code/engine.vc2008/xrGame/xrGame.vcxproj
  code/engine.vc2008/xrGame/xrGame.vcxproj.filters
  code/engine.vc2008/xrGame/xrServer_Connect.cpp
  code/engine.vc2008/xrGame/xrServer_sls_clear.cpp
  code/engine.vc2008/xrServerEntities/object_factory_register.cpp
  code/engine.vc2008/xrServerEntities/script_engine_export.h
Labels: Architecture

#136 New values in inventory states
  code/engine.vc2008/FrayBuildConfig.hpp
  code/engine.vc2008/xrGame/Actor.cpp
  code/engine.vc2008/xrGame/ui/UIActorStateInfo.cpp
  code/engine.vc2008/xrGame/ui/UIMotionIcon.cpp
  code/engine.vc2008/xrGame/ui/UIMotionIcon.h
  game/gamedata/configs/ui/actor_menu.xml
  game/gamedata/configs/ui/actor_menu_16.xml
Labels: Interface

#144 Singleton LuaVM
  code/engine.vc2008/xrGame/alife_simulator.cpp
  code/engine.vc2008/xrGame/xrGame.cpp
  code/engine.vc2008/xrRender/xrRender/ResourceManager.h
  code/engine.vc2008/xrRender/xrRender/ResourceManager_Scripting.cpp
  code/engine.vc2008/xrRender/xrRenderDX10/dx10ResourceManager_Scripting.cpp
  code/engine.vc2008/xrScripts/VMLua.cpp
  code/engine.vc2008/xrScripts/VMLua.h
  code/engine.vc2008/xrScripts/xrScripts.vcxproj
  code/engine.vc2008/xrScripts/xrScripts.vcxproj.filters
  code/engine.vc2008/xrServerEntities/script_engine.cpp
  code/engine.vc2008/xrServerEntities/script_storage.cpp
  code/engine.vc2008/xrServerEntities/script_storage.h
  code/engine.vc2008/xrServerEntities/script_storage_inline.h
Labels: Architecture

#146 Translation of comments with a bad coding system.ltx
  game/gamedata/configs/system.ltx
Labels: Community
